package com.iermu.client.business.dao.generator;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.iermu.client.business.dao.generator.AccountDao;
import com.iermu.client.business.dao.generator.AlarmImageDataDao;
import com.iermu.client.business.dao.generator.CamSettingDataDao;
import com.iermu.client.business.dao.generator.WifiInfoDao;
import com.iermu.client.business.dao.generator.CloudPositionDao;
import com.iermu.client.business.dao.generator.CamLiveDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 25): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 25;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        AccountDao.createTable(db, ifNotExists);
        AlarmImageDataDao.createTable(db, ifNotExists);
        CamSettingDataDao.createTable(db, ifNotExists);
        WifiInfoDao.createTable(db, ifNotExists);
        CloudPositionDao.createTable(db, ifNotExists);
        CamLiveDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        AccountDao.dropTable(db, ifExists);
        AlarmImageDataDao.dropTable(db, ifExists);
        CamSettingDataDao.dropTable(db, ifExists);
        WifiInfoDao.dropTable(db, ifExists);
        CloudPositionDao.dropTable(db, ifExists);
        CamLiveDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AccountDao.class);
        registerDaoClass(AlarmImageDataDao.class);
        registerDaoClass(CamSettingDataDao.class);
        registerDaoClass(WifiInfoDao.class);
        registerDaoClass(CloudPositionDao.class);
        registerDaoClass(CamLiveDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
