package com.iermu.client.business.dao.generator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.iermu.client.model.Account;
import com.iermu.client.model.AlarmImageData;
import com.iermu.client.model.CamSettingData;
import com.iermu.client.model.WifiInfo;
import com.iermu.client.model.CloudPosition;
import com.iermu.client.model.CamLive;

import com.iermu.client.business.dao.generator.AccountDao;
import com.iermu.client.business.dao.generator.AlarmImageDataDao;
import com.iermu.client.business.dao.generator.CamSettingDataDao;
import com.iermu.client.business.dao.generator.WifiInfoDao;
import com.iermu.client.business.dao.generator.CloudPositionDao;
import com.iermu.client.business.dao.generator.CamLiveDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig alarmImageDataDaoConfig;
    private final DaoConfig camSettingDataDaoConfig;
    private final DaoConfig wifiInfoDaoConfig;
    private final DaoConfig cloudPositionDaoConfig;
    private final DaoConfig camLiveDaoConfig;

    private final AccountDao accountDao;
    private final AlarmImageDataDao alarmImageDataDao;
    private final CamSettingDataDao camSettingDataDao;
    private final WifiInfoDao wifiInfoDao;
    private final CloudPositionDao cloudPositionDao;
    private final CamLiveDao camLiveDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        alarmImageDataDaoConfig = daoConfigMap.get(AlarmImageDataDao.class).clone();
        alarmImageDataDaoConfig.initIdentityScope(type);

        camSettingDataDaoConfig = daoConfigMap.get(CamSettingDataDao.class).clone();
        camSettingDataDaoConfig.initIdentityScope(type);

        wifiInfoDaoConfig = daoConfigMap.get(WifiInfoDao.class).clone();
        wifiInfoDaoConfig.initIdentityScope(type);

        cloudPositionDaoConfig = daoConfigMap.get(CloudPositionDao.class).clone();
        cloudPositionDaoConfig.initIdentityScope(type);

        camLiveDaoConfig = daoConfigMap.get(CamLiveDao.class).clone();
        camLiveDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        alarmImageDataDao = new AlarmImageDataDao(alarmImageDataDaoConfig, this);
        camSettingDataDao = new CamSettingDataDao(camSettingDataDaoConfig, this);
        wifiInfoDao = new WifiInfoDao(wifiInfoDaoConfig, this);
        cloudPositionDao = new CloudPositionDao(cloudPositionDaoConfig, this);
        camLiveDao = new CamLiveDao(camLiveDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(AlarmImageData.class, alarmImageDataDao);
        registerDao(CamSettingData.class, camSettingDataDao);
        registerDao(WifiInfo.class, wifiInfoDao);
        registerDao(CloudPosition.class, cloudPositionDao);
        registerDao(CamLive.class, camLiveDao);
    }
    
    public void clear() {
        accountDaoConfig.getIdentityScope().clear();
        alarmImageDataDaoConfig.getIdentityScope().clear();
        camSettingDataDaoConfig.getIdentityScope().clear();
        wifiInfoDaoConfig.getIdentityScope().clear();
        cloudPositionDaoConfig.getIdentityScope().clear();
        camLiveDaoConfig.getIdentityScope().clear();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public AlarmImageDataDao getAlarmImageDataDao() {
        return alarmImageDataDao;
    }

    public CamSettingDataDao getCamSettingDataDao() {
        return camSettingDataDao;
    }

    public WifiInfoDao getWifiInfoDao() {
        return wifiInfoDao;
    }

    public CloudPositionDao getCloudPositionDao() {
        return cloudPositionDao;
    }

    public CamLiveDao getCamLiveDao() {
        return camLiveDao;
    }

}
