package com.iermu.client.business.dao.generator;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.iermu.client.model.WifiInfo;
import com.iermu.client.model.WifiInfo.Builder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WIFI_INFO".
*/
public class WifiInfoDao extends AbstractDao<WifiInfo, Long> {

    public static final String TABLENAME = "WIFI_INFO";

    /**
     * Properties of entity WifiInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ssid = new Property(1, String.class, "ssid", false, "SSID");
        public final static Property Account = new Property(2, String.class, "account", false, "ACCOUNT");
        public final static Property Pass = new Property(3, String.class, "pass", false, "PASS");
    };


    public WifiInfoDao(DaoConfig config) {
        super(config);
    }
    
    public WifiInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WIFI_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SSID\" TEXT UNIQUE ," + // 1: ssid
                "\"ACCOUNT\" TEXT," + // 2: account
                "\"PASS\" TEXT);"); // 3: pass
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WIFI_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WifiInfo entity) {
        stmt.clearBindings();
        if(entity.hasId()) {
            stmt.bindLong(1, entity.getId());
        }
        if(entity.hasSsid()) {
            stmt.bindString(2, entity.getSsid());
        }
        if(entity.hasAccount()) {
            stmt.bindString(3, entity.getAccount());
        }
        if(entity.hasPass()) {
            stmt.bindString(4, entity.getPass());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WifiInfo readEntity(Cursor cursor, int offset) {
        Builder builder = WifiInfo.newBuilder();
        if (!cursor.isNull(offset + 0)) {
            builder.setId(cursor.getLong(offset + 0));
        }
        if (!cursor.isNull(offset + 1)) {
            builder.setSsid(cursor.getString(offset + 1));
        }
        if (!cursor.isNull(offset + 2)) {
            builder.setAccount(cursor.getString(offset + 2));
        }
        if (!cursor.isNull(offset + 3)) {
            builder.setPass(cursor.getString(offset + 3));
        }
        return builder.build();
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WifiInfo entity, int offset) {
        throw new UnsupportedOperationException("Protobuf objects cannot be modified");
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WifiInfo entity, long rowId) {
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WifiInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return false;
    }
    
}
